// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ipstate.proto

package ipstate

import (
	context "context"
	fmt "fmt"
	ipprovider "github.com/cisco-app-networking/nsm-nse/api/ipam/ipprovider"
	ipreceiver "github.com/cisco-app-networking/nsm-nse/api/ipam/ipreceiver"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubnetsState struct {
	Subnet               []*ipprovider.Subnet `protobuf:"bytes,1,rep,name=subnet,proto3" json:"subnet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SubnetsState) Reset()         { *m = SubnetsState{} }
func (m *SubnetsState) String() string { return proto.CompactTextString(m) }
func (*SubnetsState) ProtoMessage()    {}
func (*SubnetsState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9c757518148bec6, []int{0}
}

func (m *SubnetsState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubnetsState.Unmarshal(m, b)
}
func (m *SubnetsState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubnetsState.Marshal(b, m, deterministic)
}
func (m *SubnetsState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubnetsState.Merge(m, src)
}
func (m *SubnetsState) XXX_Size() int {
	return xxx_messageInfo_SubnetsState.Size(m)
}
func (m *SubnetsState) XXX_DiscardUnknown() {
	xxx_messageInfo_SubnetsState.DiscardUnknown(m)
}

var xxx_messageInfo_SubnetsState proto.InternalMessageInfo

func (m *SubnetsState) GetSubnet() []*ipprovider.Subnet {
	if m != nil {
		return m.Subnet
	}
	return nil
}

type IpRangesState struct {
	Range                []*ipreceiver.IpRange `protobuf:"bytes,1,rep,name=range,proto3" json:"range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *IpRangesState) Reset()         { *m = IpRangesState{} }
func (m *IpRangesState) String() string { return proto.CompactTextString(m) }
func (*IpRangesState) ProtoMessage()    {}
func (*IpRangesState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9c757518148bec6, []int{1}
}

func (m *IpRangesState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IpRangesState.Unmarshal(m, b)
}
func (m *IpRangesState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IpRangesState.Marshal(b, m, deterministic)
}
func (m *IpRangesState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IpRangesState.Merge(m, src)
}
func (m *IpRangesState) XXX_Size() int {
	return xxx_messageInfo_IpRangesState.Size(m)
}
func (m *IpRangesState) XXX_DiscardUnknown() {
	xxx_messageInfo_IpRangesState.DiscardUnknown(m)
}

var xxx_messageInfo_IpRangesState proto.InternalMessageInfo

func (m *IpRangesState) GetRange() []*ipreceiver.IpRange {
	if m != nil {
		return m.Range
	}
	return nil
}

type SubnetIdentifier struct {
	AddrFamily           *ipprovider.IpFamily `protobuf:"bytes,1,opt,name=addr_family,json=addrFamily,proto3" json:"addr_family,omitempty"`
	ConnectivityDomain   string               `protobuf:"bytes,2,opt,name=connectivity_domain,json=connectivityDomain,proto3" json:"connectivity_domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SubnetIdentifier) Reset()         { *m = SubnetIdentifier{} }
func (m *SubnetIdentifier) String() string { return proto.CompactTextString(m) }
func (*SubnetIdentifier) ProtoMessage()    {}
func (*SubnetIdentifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9c757518148bec6, []int{2}
}

func (m *SubnetIdentifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubnetIdentifier.Unmarshal(m, b)
}
func (m *SubnetIdentifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubnetIdentifier.Marshal(b, m, deterministic)
}
func (m *SubnetIdentifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubnetIdentifier.Merge(m, src)
}
func (m *SubnetIdentifier) XXX_Size() int {
	return xxx_messageInfo_SubnetIdentifier.Size(m)
}
func (m *SubnetIdentifier) XXX_DiscardUnknown() {
	xxx_messageInfo_SubnetIdentifier.DiscardUnknown(m)
}

var xxx_messageInfo_SubnetIdentifier proto.InternalMessageInfo

func (m *SubnetIdentifier) GetAddrFamily() *ipprovider.IpFamily {
	if m != nil {
		return m.AddrFamily
	}
	return nil
}

func (m *SubnetIdentifier) GetConnectivityDomain() string {
	if m != nil {
		return m.ConnectivityDomain
	}
	return ""
}

func init() {
	proto.RegisterType((*SubnetsState)(nil), "ippool.SubnetsState")
	proto.RegisterType((*IpRangesState)(nil), "ippool.IpRangesState")
	proto.RegisterType((*SubnetIdentifier)(nil), "ippool.SubnetIdentifier")
}

func init() { proto.RegisterFile("ipstate.proto", fileDescriptor_b9c757518148bec6) }

var fileDescriptor_b9c757518148bec6 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x4f, 0xfa, 0x40,
	0x10, 0xc5, 0xff, 0xfd, 0x1b, 0x31, 0x2c, 0xa2, 0x64, 0x91, 0xa4, 0xe1, 0x44, 0x9a, 0x68, 0xb8,
	0xd0, 0x46, 0x4c, 0xb8, 0x6b, 0x8c, 0xa4, 0x89, 0xa7, 0x72, 0xf3, 0x42, 0x96, 0xed, 0x50, 0x27,
	0xb6, 0xbb, 0x9b, 0xed, 0x50, 0xc3, 0x47, 0xf2, 0x5b, 0x1a, 0xba, 0x25, 0x80, 0x07, 0x0f, 0xde,
	0x66, 0xfa, 0x66, 0x7e, 0x99, 0xf7, 0xba, 0xac, 0x8b, 0xa6, 0x24, 0x41, 0x10, 0x1a, 0xab, 0x49,
	0xf3, 0x16, 0x1a, 0xa3, 0x75, 0x3e, 0x7c, 0xcd, 0x90, 0xde, 0x37, 0xab, 0x50, 0xea, 0x22, 0x92,
	0x58, 0x4a, 0x3d, 0x11, 0xc6, 0x4c, 0x14, 0xd0, 0xa7, 0xb6, 0x1f, 0xa8, 0xb2, 0x48, 0x95, 0xc5,
	0x44, 0x95, 0x10, 0x09, 0x83, 0x11, 0x1a, 0x51, 0x44, 0x68, 0x8c, 0xd5, 0x15, 0xa6, 0x60, 0x8f,
	0x4a, 0x47, 0xfd, 0x13, 0xcd, 0x82, 0x04, 0xac, 0x6a, 0xda, 0xbe, 0x74, 0xb4, 0x60, 0xc6, 0x2e,
	0x17, 0x9b, 0x95, 0x02, 0x2a, 0x17, 0xbb, 0xcb, 0xf9, 0x1d, 0x6b, 0x95, 0x75, 0xef, 0x7b, 0xa3,
	0xb3, 0x71, 0x67, 0x7a, 0x15, 0x3a, 0x13, 0xa1, 0x9b, 0x4a, 0x1a, 0x35, 0x98, 0xb1, 0x6e, 0x6c,
	0x12, 0xa1, 0x32, 0x68, 0x16, 0x6f, 0xd9, 0xb9, 0xdd, 0xb5, 0xcd, 0xde, 0xf5, 0x7e, 0xaf, 0x99,
	0x4a, 0x9c, 0x1a, 0x54, 0xac, 0xe7, 0x48, 0x71, 0x0a, 0x8a, 0x70, 0x8d, 0x60, 0xf9, 0x3d, 0xeb,
	0x88, 0x34, 0xb5, 0xcb, 0xb5, 0x28, 0x30, 0xdf, 0xfa, 0xde, 0xc8, 0x1b, 0x77, 0xa6, 0xbd, 0x03,
	0xe0, 0xa5, 0xfe, 0x9e, 0xb0, 0xdd, 0x90, 0xab, 0x79, 0xc4, 0xfa, 0x52, 0x2b, 0x05, 0x92, 0xb0,
	0x42, 0xda, 0x2e, 0x53, 0x5d, 0x08, 0x54, 0xfe, 0xff, 0x91, 0x37, 0x6e, 0x27, 0xfc, 0x58, 0x7a,
	0xae, 0x95, 0xe9, 0x97, 0xc7, 0x06, 0xb1, 0x11, 0x45, 0x7d, 0x6c, 0xac, 0x08, 0xac, 0xd5, 0x99,
	0x20, 0x6d, 0xf9, 0x9c, 0xf5, 0xe7, 0x40, 0x8f, 0x79, 0xae, 0xa5, 0x20, 0x48, 0x9b, 0x34, 0xb8,
	0x7f, 0x6a, 0xfc, 0x70, 0xee, 0xf0, 0xe6, 0x54, 0x71, 0xfe, 0x83, 0x7f, 0x7c, 0xce, 0xf8, 0x31,
	0xc8, 0x85, 0xf3, 0x0b, 0x67, 0xf0, 0x23, 0xa2, 0x3d, 0xe8, 0xa9, 0xfd, 0x76, 0xd1, 0x3c, 0xa4,
	0x55, 0xab, 0xfe, 0x4b, 0x0f, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x94, 0x0a, 0x07, 0xd7, 0x5a,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IpamStateInterrogatorClient is the client API for IpamStateInterrogator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IpamStateInterrogatorClient interface {
	GetAllocatedSubnets(ctx context.Context, in *SubnetIdentifier, opts ...grpc.CallOption) (*SubnetsState, error)
	GetAllocatedRanges(ctx context.Context, in *SubnetIdentifier, opts ...grpc.CallOption) (*IpRangesState, error)
}

type ipamStateInterrogatorClient struct {
	cc *grpc.ClientConn
}

func NewIpamStateInterrogatorClient(cc *grpc.ClientConn) IpamStateInterrogatorClient {
	return &ipamStateInterrogatorClient{cc}
}

func (c *ipamStateInterrogatorClient) GetAllocatedSubnets(ctx context.Context, in *SubnetIdentifier, opts ...grpc.CallOption) (*SubnetsState, error) {
	out := new(SubnetsState)
	err := c.cc.Invoke(ctx, "/ippool.IpamStateInterrogator/GetAllocatedSubnets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipamStateInterrogatorClient) GetAllocatedRanges(ctx context.Context, in *SubnetIdentifier, opts ...grpc.CallOption) (*IpRangesState, error) {
	out := new(IpRangesState)
	err := c.cc.Invoke(ctx, "/ippool.IpamStateInterrogator/GetAllocatedRanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IpamStateInterrogatorServer is the server API for IpamStateInterrogator service.
type IpamStateInterrogatorServer interface {
	GetAllocatedSubnets(context.Context, *SubnetIdentifier) (*SubnetsState, error)
	GetAllocatedRanges(context.Context, *SubnetIdentifier) (*IpRangesState, error)
}

// UnimplementedIpamStateInterrogatorServer can be embedded to have forward compatible implementations.
type UnimplementedIpamStateInterrogatorServer struct {
}

func (*UnimplementedIpamStateInterrogatorServer) GetAllocatedSubnets(ctx context.Context, req *SubnetIdentifier) (*SubnetsState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllocatedSubnets not implemented")
}
func (*UnimplementedIpamStateInterrogatorServer) GetAllocatedRanges(ctx context.Context, req *SubnetIdentifier) (*IpRangesState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllocatedRanges not implemented")
}

func RegisterIpamStateInterrogatorServer(s *grpc.Server, srv IpamStateInterrogatorServer) {
	s.RegisterService(&_IpamStateInterrogator_serviceDesc, srv)
}

func _IpamStateInterrogator_GetAllocatedSubnets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpamStateInterrogatorServer).GetAllocatedSubnets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ippool.IpamStateInterrogator/GetAllocatedSubnets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpamStateInterrogatorServer).GetAllocatedSubnets(ctx, req.(*SubnetIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpamStateInterrogator_GetAllocatedRanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpamStateInterrogatorServer).GetAllocatedRanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ippool.IpamStateInterrogator/GetAllocatedRanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpamStateInterrogatorServer).GetAllocatedRanges(ctx, req.(*SubnetIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

var _IpamStateInterrogator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ippool.IpamStateInterrogator",
	HandlerType: (*IpamStateInterrogatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllocatedSubnets",
			Handler:    _IpamStateInterrogator_GetAllocatedSubnets_Handler,
		},
		{
			MethodName: "GetAllocatedRanges",
			Handler:    _IpamStateInterrogator_GetAllocatedRanges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ipstate.proto",
}
