# Default values for vl3.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registry: docker.io
org: ciscoappnetworking
tag: master
pullPolicy: IfNotPresent
vppMetricsPort: 9191
metricsPort: 2112
insecure: true

nseControl:
  nsr:
    port: 5005
    addr: vl3-service.wcm-cisco.com
    cd: vl3-service-connectivity-domain
  # nameserver: 1.2.3.4
  # dnszone: cappnet-example.com
  ipam:
    defaultPrefixPool: 192.168.0.0/16
    prefixLength: 22
    serverAddress: ipam-vl3-service.wcm-cisco.com:50051

nsm:
  serviceName: vl3-service

global:

replicaCount: 1

image:
  repository: tiswanso
  tag: master
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
