// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: serviceregistry.proto

package serviceregistry

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EventType int32

const (
	EventType_Register EventType = 0
	EventType_Remove   EventType = 1
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "Register",
		1: "Remove",
	}
	EventType_value = map[string]int32{
		"Register": 0,
		"Remove":   1,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_serviceregistry_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_serviceregistry_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_serviceregistry_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviceregistry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_serviceregistry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_serviceregistry_proto_rawDescGZIP(), []int{0}
}

type WorkloadEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType       EventType        `protobuf:"varint,1,opt,name=eventType,proto3,enum=svreg.EventType" json:"eventType,omitempty"`
	ServiceWorkload *ServiceWorkload `protobuf:"bytes,2,opt,name=serviceWorkload,proto3" json:"serviceWorkload,omitempty"`
}

func (x *WorkloadEvent) Reset() {
	*x = WorkloadEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviceregistry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkloadEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadEvent) ProtoMessage() {}

func (x *WorkloadEvent) ProtoReflect() protoreflect.Message {
	mi := &file_serviceregistry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadEvent.ProtoReflect.Descriptor instead.
func (*WorkloadEvent) Descriptor() ([]byte, []int) {
	return file_serviceregistry_proto_rawDescGZIP(), []int{1}
}

func (x *WorkloadEvent) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_Register
}

func (x *WorkloadEvent) GetServiceWorkload() *ServiceWorkload {
	if x != nil {
		return x.ServiceWorkload
	}
	return nil
}

//The request used to register a new service or update the existing ones
type ServiceWorkload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName        string      `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	ConnectivityDomain string      `protobuf:"bytes,2,opt,name=connectivityDomain,proto3" json:"connectivityDomain,omitempty"`
	Workloads          []*Workload `protobuf:"bytes,3,rep,name=workloads,proto3" json:"workloads,omitempty"`
	Ports              []int32     `protobuf:"varint,4,rep,packed,name=ports,proto3" json:"ports,omitempty"`
}

func (x *ServiceWorkload) Reset() {
	*x = ServiceWorkload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviceregistry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceWorkload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceWorkload) ProtoMessage() {}

func (x *ServiceWorkload) ProtoReflect() protoreflect.Message {
	mi := &file_serviceregistry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceWorkload.ProtoReflect.Descriptor instead.
func (*ServiceWorkload) Descriptor() ([]byte, []int) {
	return file_serviceregistry_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceWorkload) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceWorkload) GetConnectivityDomain() string {
	if x != nil {
		return x.ConnectivityDomain
	}
	return ""
}

func (x *ServiceWorkload) GetWorkloads() []*Workload {
	if x != nil {
		return x.Workloads
	}
	return nil
}

func (x *ServiceWorkload) GetPorts() []int32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

//Basic workload
type Workload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier *WorkloadIdentifier `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	IPAddress  []string            `protobuf:"bytes,2,rep,name=IPAddress,proto3" json:"IPAddress,omitempty"`
}

func (x *Workload) Reset() {
	*x = Workload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviceregistry_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Workload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workload) ProtoMessage() {}

func (x *Workload) ProtoReflect() protoreflect.Message {
	mi := &file_serviceregistry_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workload.ProtoReflect.Descriptor instead.
func (*Workload) Descriptor() ([]byte, []int) {
	return file_serviceregistry_proto_rawDescGZIP(), []int{3}
}

func (x *Workload) GetIdentifier() *WorkloadIdentifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *Workload) GetIPAddress() []string {
	if x != nil {
		return x.IPAddress
	}
	return nil
}

type WorkloadIdentifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cluster string `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	PodName string `protobuf:"bytes,2,opt,name=podName,proto3" json:"podName,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	NseName string `protobuf:"bytes,4,opt,name=nseName,proto3" json:"nseName,omitempty"`
}

func (x *WorkloadIdentifier) Reset() {
	*x = WorkloadIdentifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviceregistry_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkloadIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadIdentifier) ProtoMessage() {}

func (x *WorkloadIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_serviceregistry_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadIdentifier.ProtoReflect.Descriptor instead.
func (*WorkloadIdentifier) Descriptor() ([]byte, []int) {
	return file_serviceregistry_proto_rawDescGZIP(), []int{4}
}

func (x *WorkloadIdentifier) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *WorkloadIdentifier) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *WorkloadIdentifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkloadIdentifier) GetNseName() string {
	if x != nil {
		return x.NseName
	}
	return ""
}

type RegisteredWorkloads struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Workloads []*ServiceWorkload `protobuf:"bytes,1,rep,name=Workloads,proto3" json:"Workloads,omitempty"`
}

func (x *RegisteredWorkloads) Reset() {
	*x = RegisteredWorkloads{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviceregistry_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisteredWorkloads) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredWorkloads) ProtoMessage() {}

func (x *RegisteredWorkloads) ProtoReflect() protoreflect.Message {
	mi := &file_serviceregistry_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredWorkloads.ProtoReflect.Descriptor instead.
func (*RegisteredWorkloads) Descriptor() ([]byte, []int) {
	return file_serviceregistry_proto_rawDescGZIP(), []int{5}
}

func (x *RegisteredWorkloads) GetWorkloads() []*ServiceWorkload {
	if x != nil {
		return x.Workloads
	}
	return nil
}

var File_serviceregistry_proto protoreflect.FileDescriptor

var file_serviceregistry_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x76, 0x72, 0x65, 0x67, 0x22, 0x07,
	0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x81, 0x01, 0x0a, 0x0d, 0x57, 0x6f, 0x72, 0x6b,
	0x6c, 0x6f, 0x61, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x09, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x73,
	0x76, 0x72, 0x65, 0x67, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x40, 0x0a, 0x0f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x76, 0x72, 0x65, 0x67, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x0f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xa8, 0x01, 0x0a, 0x0f,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x2e, 0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x12, 0x2d, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x76, 0x72, 0x65, 0x67, 0x2e, 0x57, 0x6f, 0x72,
	0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x22, 0x63, 0x0a, 0x08, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x76, 0x72, 0x65, 0x67, 0x2e, 0x57,
	0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x1c, 0x0a,
	0x09, 0x49, 0x50, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x49, 0x50, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x76, 0x0a, 0x12, 0x57,
	0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6f,
	0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x73, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x73, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x4b, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65,
	0x64, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x12, 0x34, 0x0a, 0x09, 0x57, 0x6f,
	0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x73, 0x76, 0x72, 0x65, 0x67, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x57, 0x6f, 0x72,
	0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x09, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x73,
	0x2a, 0x25, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a,
	0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x10, 0x01, 0x32, 0xb7, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x12, 0x3a, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x2e, 0x73, 0x76, 0x72, 0x65, 0x67,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64,
	0x1a, 0x0c, 0x2e, 0x73, 0x76, 0x72, 0x65, 0x67, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x35, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12,
	0x0c, 0x2e, 0x73, 0x76, 0x72, 0x65, 0x67, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e,
	0x73, 0x76, 0x72, 0x65, 0x67, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x22, 0x00, 0x30, 0x01, 0x12, 0x38, 0x0a, 0x0e, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x2e, 0x73, 0x76, 0x72, 0x65,
	0x67, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61,
	0x64, 0x1a, 0x0c, 0x2e, 0x73, 0x76, 0x72, 0x65, 0x67, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x32, 0x55, 0x0a, 0x0d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x44, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x65, 0x64, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x12, 0x0c, 0x2e, 0x73,
	0x76, 0x72, 0x65, 0x67, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1a, 0x2e, 0x73, 0x76, 0x72,
	0x65, 0x67, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x57, 0x6f, 0x72,
	0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_serviceregistry_proto_rawDescOnce sync.Once
	file_serviceregistry_proto_rawDescData = file_serviceregistry_proto_rawDesc
)

func file_serviceregistry_proto_rawDescGZIP() []byte {
	file_serviceregistry_proto_rawDescOnce.Do(func() {
		file_serviceregistry_proto_rawDescData = protoimpl.X.CompressGZIP(file_serviceregistry_proto_rawDescData)
	})
	return file_serviceregistry_proto_rawDescData
}

var file_serviceregistry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_serviceregistry_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_serviceregistry_proto_goTypes = []interface{}{
	(EventType)(0),              // 0: svreg.EventType
	(*Empty)(nil),               // 1: svreg.Empty
	(*WorkloadEvent)(nil),       // 2: svreg.WorkloadEvent
	(*ServiceWorkload)(nil),     // 3: svreg.ServiceWorkload
	(*Workload)(nil),            // 4: svreg.Workload
	(*WorkloadIdentifier)(nil),  // 5: svreg.WorkloadIdentifier
	(*RegisteredWorkloads)(nil), // 6: svreg.RegisteredWorkloads
}
var file_serviceregistry_proto_depIdxs = []int32{
	0, // 0: svreg.WorkloadEvent.eventType:type_name -> svreg.EventType
	3, // 1: svreg.WorkloadEvent.serviceWorkload:type_name -> svreg.ServiceWorkload
	4, // 2: svreg.ServiceWorkload.workloads:type_name -> svreg.Workload
	5, // 3: svreg.Workload.identifier:type_name -> svreg.WorkloadIdentifier
	3, // 4: svreg.RegisteredWorkloads.Workloads:type_name -> svreg.ServiceWorkload
	3, // 5: svreg.Registry.RegisterWorkload:input_type -> svreg.ServiceWorkload
	1, // 6: svreg.Registry.GetServices:input_type -> svreg.Empty
	3, // 7: svreg.Registry.RemoveWorkload:input_type -> svreg.ServiceWorkload
	1, // 8: svreg.RegistryState.GetRegisteredWorkloads:input_type -> svreg.Empty
	1, // 9: svreg.Registry.RegisterWorkload:output_type -> svreg.Empty
	2, // 10: svreg.Registry.GetServices:output_type -> svreg.WorkloadEvent
	1, // 11: svreg.Registry.RemoveWorkload:output_type -> svreg.Empty
	6, // 12: svreg.RegistryState.GetRegisteredWorkloads:output_type -> svreg.RegisteredWorkloads
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_serviceregistry_proto_init() }
func file_serviceregistry_proto_init() {
	if File_serviceregistry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_serviceregistry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviceregistry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkloadEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviceregistry_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceWorkload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviceregistry_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Workload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviceregistry_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkloadIdentifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviceregistry_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisteredWorkloads); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_serviceregistry_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_serviceregistry_proto_goTypes,
		DependencyIndexes: file_serviceregistry_proto_depIdxs,
		EnumInfos:         file_serviceregistry_proto_enumTypes,
		MessageInfos:      file_serviceregistry_proto_msgTypes,
	}.Build()
	File_serviceregistry_proto = out.File
	file_serviceregistry_proto_rawDesc = nil
	file_serviceregistry_proto_goTypes = nil
	file_serviceregistry_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RegistryClient is the client API for Registry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistryClient interface {
	RegisterWorkload(ctx context.Context, in *ServiceWorkload, opts ...grpc.CallOption) (*Empty, error)
	GetServices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Registry_GetServicesClient, error)
	RemoveWorkload(ctx context.Context, in *ServiceWorkload, opts ...grpc.CallOption) (*Empty, error)
}

type registryClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryClient(cc grpc.ClientConnInterface) RegistryClient {
	return &registryClient{cc}
}

func (c *registryClient) RegisterWorkload(ctx context.Context, in *ServiceWorkload, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/svreg.Registry/RegisterWorkload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) GetServices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Registry_GetServicesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Registry_serviceDesc.Streams[0], "/svreg.Registry/GetServices", opts...)
	if err != nil {
		return nil, err
	}
	x := &registryGetServicesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Registry_GetServicesClient interface {
	Recv() (*WorkloadEvent, error)
	grpc.ClientStream
}

type registryGetServicesClient struct {
	grpc.ClientStream
}

func (x *registryGetServicesClient) Recv() (*WorkloadEvent, error) {
	m := new(WorkloadEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *registryClient) RemoveWorkload(ctx context.Context, in *ServiceWorkload, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/svreg.Registry/RemoveWorkload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServer is the server API for Registry service.
type RegistryServer interface {
	RegisterWorkload(context.Context, *ServiceWorkload) (*Empty, error)
	GetServices(*Empty, Registry_GetServicesServer) error
	RemoveWorkload(context.Context, *ServiceWorkload) (*Empty, error)
}

// UnimplementedRegistryServer can be embedded to have forward compatible implementations.
type UnimplementedRegistryServer struct {
}

func (*UnimplementedRegistryServer) RegisterWorkload(context.Context, *ServiceWorkload) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWorkload not implemented")
}
func (*UnimplementedRegistryServer) GetServices(*Empty, Registry_GetServicesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetServices not implemented")
}
func (*UnimplementedRegistryServer) RemoveWorkload(context.Context, *ServiceWorkload) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveWorkload not implemented")
}

func RegisterRegistryServer(s *grpc.Server, srv RegistryServer) {
	s.RegisterService(&_Registry_serviceDesc, srv)
}

func _Registry_RegisterWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceWorkload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).RegisterWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/svreg.Registry/RegisterWorkload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).RegisterWorkload(ctx, req.(*ServiceWorkload))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_GetServices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RegistryServer).GetServices(m, &registryGetServicesServer{stream})
}

type Registry_GetServicesServer interface {
	Send(*WorkloadEvent) error
	grpc.ServerStream
}

type registryGetServicesServer struct {
	grpc.ServerStream
}

func (x *registryGetServicesServer) Send(m *WorkloadEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _Registry_RemoveWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceWorkload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).RemoveWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/svreg.Registry/RemoveWorkload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).RemoveWorkload(ctx, req.(*ServiceWorkload))
	}
	return interceptor(ctx, in, info, handler)
}

var _Registry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "svreg.Registry",
	HandlerType: (*RegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorkload",
			Handler:    _Registry_RegisterWorkload_Handler,
		},
		{
			MethodName: "RemoveWorkload",
			Handler:    _Registry_RemoveWorkload_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetServices",
			Handler:       _Registry_GetServices_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "serviceregistry.proto",
}

// RegistryStateClient is the client API for RegistryState service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistryStateClient interface {
	GetRegisteredWorkloads(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RegisteredWorkloads, error)
}

type registryStateClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryStateClient(cc grpc.ClientConnInterface) RegistryStateClient {
	return &registryStateClient{cc}
}

func (c *registryStateClient) GetRegisteredWorkloads(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RegisteredWorkloads, error) {
	out := new(RegisteredWorkloads)
	err := c.cc.Invoke(ctx, "/svreg.RegistryState/GetRegisteredWorkloads", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryStateServer is the server API for RegistryState service.
type RegistryStateServer interface {
	GetRegisteredWorkloads(context.Context, *Empty) (*RegisteredWorkloads, error)
}

// UnimplementedRegistryStateServer can be embedded to have forward compatible implementations.
type UnimplementedRegistryStateServer struct {
}

func (*UnimplementedRegistryStateServer) GetRegisteredWorkloads(context.Context, *Empty) (*RegisteredWorkloads, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegisteredWorkloads not implemented")
}

func RegisterRegistryStateServer(s *grpc.Server, srv RegistryStateServer) {
	s.RegisterService(&_RegistryState_serviceDesc, srv)
}

func _RegistryState_GetRegisteredWorkloads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryStateServer).GetRegisteredWorkloads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/svreg.RegistryState/GetRegisteredWorkloads",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryStateServer).GetRegisteredWorkloads(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _RegistryState_serviceDesc = grpc.ServiceDesc{
	ServiceName: "svreg.RegistryState",
	HandlerType: (*RegistryStateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRegisteredWorkloads",
			Handler:    _RegistryState_GetRegisteredWorkloads_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serviceregistry.proto",
}
